### PR TITLE
Add ADS frank methods paper link

### LINKED ISSUE #42: add ADS links
Update README and `index.rst` (including sidebar link to papers citing frank) once we have links.

### PR DESCRIPTION
**Pull request by jeffjennings**
Adds the link to the repo README and the docs' index

Fixes #42

### CODE REVIEW

**Comment by rbooth200** [comment]
I don't think this is the final ADS link. I can accept the PR, but we shouldn't close the issue.

**Comment by jeffjennings** [comment]
I checked with another paper that the ADS link with the arxiv identifier in the link redirects to the updated ADS link with the jouranl identifier, so I think the current link is persistent.

**Comment by rbooth200** [comment]
Can you find confirmation on ADS that this is always true?

**Comment by jeffjennings** [comment]
This excerpt from http://adsabs.harvard.edu/abs_doc/faq.html is roughly similar.
_Preprints_
_Preprints submitted to the arXiv and which are cited using the proper identifier (e.g. astro-ph/0012345) will be properly assigned to the e-print record in question. If the e-print has been matched to its corresponding published paper, the citation will be "transferred" to the published paper, which in ADS is considered the canonical record for the paper in question._

You can see it works e.g. with this MNRAS paper, 
_https://ui.adsabs.harvard.edu/abs/2018arXiv180300571J/abstract_ redirects to https://ui.adsabs.harvard.edu/abs/2018MNRAS.477.4131J/abstract

**Comment by rbooth200** [comment]
Ok, we can always correct it later if we find a problem.

**Pull request merged**
