### PR TITLE
Added variable output types

### PR DESCRIPTION
**Pull request by rbooth200**
This pull request implements multiple output formats for the frank fit. 

We should wait for #55 before proceeding here.

### CODE REVIEW

**Comment by jeffjennings** [comment]
Would you mind allowing `txt` or `dat` for the ascii formats? `.dat` is common for UVTables.

**Comment by rbooth200** [comment]
What format is .dat?

**Comment by jeffjennings** [comment]
just an ascii format, https://help.ceda.ac.uk/article/4429-ascii-formats

**Comment by rbooth200** [comment]
Ok, .dat is sometimes used for binary too. I've added it as an alias of txt

**Comment by rbooth200** [comment]
You've done it now, so I wouldn't undo it - but probably we're going to get a bunch of conflicts from the changes to the formatting. It would have been best to do that as a separate PR after this and #55

**Comment by jeffjennings** [comment]
my branch also has the unformatted `.json`s, so I think we might avoid conflicts

**Comment by rbooth200** [comment]
Ok

**Comment by jeffjennings** [comment]
should I merge?

**Comment by rbooth200** [comment]
Yes

**Pull request merged**
