### PR TITLE
Update version to 1.0.0

### PR DESCRIPTION
**Pull request by rbooth200**
This is one of a tranch of PRs I'm generating to cover the remaining issues for version 1.0.0 milestone. 
This should probably be the last one to go.

### CODE REVIEW

**Comment by jeffjennings** [comment]
Jeff: Let's do make this the last PR to go. It should address and close the minor issues related to deploying version 1.0.0:
Fixes #42, Fixes #43, Fixes #81

**Comment by rbooth200** [comment]
We should remove the WARNINGs about the code being in development and push to PYPI before doing this PR

**Comment by rbooth200** [comment]
There are also some images / links that need fixing in the README

**Comment by rbooth200** [comment]
Quick Q: Is there meant to be an image here? There's a copyright message about it in the README?

**Comment by jeffjennings** [comment]
> Quick Q: Is there meant to be an image here? There's a copyright message about it in the README.

Yes the logo was commented, and what an image it is. Thanks for catching!

**Comment by rbooth200** [comment]
Ok, I've implemented a solution to get the coverage reports but it won't work properly until the branch is merged. The idea is to store the reports and the badge alongside the docs website. Since the website is only updated on the master branch the links in the readme won't work until merge.

**Comment by rbooth200** [comment]
I think this branch is ready to go now. Is there anything else we should do before updating the version number? There are a couple of remaining issues open...

**Comment by jeffjennings** [comment]
I've updated my comment above that closes all issues except #42. We could wait for the arxiv link, but I could open a separate branch for that and to update the Zenodo link in the docs' `index.rst`. 

For now I've just commented the links to MNRAS and ADS in the README. 

I think it's ready; the links don't need to hold up v1.0. I'll still wait to upload master to pypi until we have the arxiv link on master.

**Comment by rbooth200** [comment]
Sounds good

**Pull request merged**
