### PR TITLE
Update quickstart

### PR DESCRIPTION
**Pull request by jeffjennings**
This PR updates the full fit figure and corrects a couple typos in `quickstart.rst`.

It also corrects a typo in `tests.py`.

### CODE REVIEW

**Comment by jeffjennings** [comment]
I think the 'Matrix tests on CI' branch has to be merged, and then master merged into this branch ('quickstart'), to prevent the tests from trying Python 3.6 - 3.8.

**Comment by rbooth200** [comment]
I think that's right...

**Comment by jeffjennings** [comment]
Cool! If you have time to review this PR quickly while you're here, it's small.

**Comment by rbooth200** [comment]
It looks fine - no point in adding a review because it will go stale after the merge.

**Comment by jeffjennings** [comment]
ah ok good point, I'll wait for that. thanks!

**Pull request merged**
