### PR TITLE
Corrected phase centre shift signs

### LINKED ISSUE #57: Ensure code uses RA, Dec sign convention consistent with galario
Update docstrings in `geometry.py` that note the sign convention

### PR DESCRIPTION
**Pull request by rbooth200**
Fixes #57 and #107

### CODE REVIEW

**Comment by rbooth200** [comment]
I've updated the doc strings. No matter where the code was changed it was necessary to update _fit_geometry_gaussian

**Comment by rbooth200** [comment]
The tests are now passing

**Comment by rbooth200** [comment]
Fine by me.

**Comment by jeffjennings** [comment]
Cool, thanks for looking into this.

**Pull request merged**
