### PR TITLE
Docstrings

### PR DESCRIPTION
**Pull request by jeffjennings**
Fixes a couple typos in docstrings and adds a few parameters into them that are missing

### CODE REVIEW

**Comment by jeffjennings** [comment]
Hey Richard, there are a few parameters missing descriptions in docstrings in `statistical_models` and `minimizer`; I added blank entries for them in f4c0c03. Could you add descriptions when you get a chance (unless these parameters/functions will change in the next big update)?

**Comment by rbooth200** [comment]
I'll try to do it tomorrow.

**Comment by rbooth200** [comment]
Ok I added some paramaters, let me know there are others that I missed. I purposely left out definitions for conventially named parameters (`q`, `p`, etc.) in private functions.

**Comment by rbooth200** [comment]
Unfortunately I'd added the commit to the wrong branch.. Its been copied here now.

**Review by rbooth200 — APPROVED** [review]
I don't know if you plan to make more changes here, but I'm happy for this to go so I'm giving it my approval

**Comment by jeffjennings** [comment]
Great, thank you!

**Pull request merged**
