### PR TITLE
quick_fig: ensure frank fit plots in front of data

### PR DESCRIPTION
**Pull request by jeffjennings**
Very minor change in `make_quick_fig` to ensure fit line plots in front of binned visibilities

### CODE REVIEW

**Comment by rbooth200** [comment]
Can you upload a before / after plot?

**Comment by jeffjennings** [comment]
Yeah sure, before (current `master`) and after (this branch):
SR4_continuum_frank_fit_quick_after
SR4_continuum_frank_fit_quick_before

**Comment by rbooth200** [comment]
Does it make sense to have the binned data at the front?

**Comment by jeffjennings** [comment]
I don't think so, in that case you can't see the fit line clearly, even with fairly large bins. If the fit line is instead in front, it's still clear where the data are, as their marker styles are '+' and 'x'.

**Comment by rbooth200** [comment]
I guess I was just thinking the 50 k\lambda bins. But anyway, I do not have a strong opinion either way.

**Review by rbooth200 — APPROVED** [review]

**Pull request merged**
