### PR TITLE
URGENT: pre-release README warning

### PR DESCRIPTION
**Pull request by jeffjennings**
This PR quickly updates the README to be more direct that the code is still under construction (pre-v1.0). I ask that this be merged into master now so that those who find the repo understand the code isn't fully public yet.

### CODE REVIEW

**Comment by mtazzari** [comment]
I'm fine with the README changes but I'd caution about changing the default Rout as well. 
3" seems more conservative than 2" and I am in favor of it, unless the change causes side effects at runtime (e.g. fit, plots change behaviour..).
Just make sure with @rbooth200 that it is fine to change the default.

**Comment by rbooth200** [comment]
I'd like more justification for 3" instead of 2". One of the manuscript or the default needs to be changed to be consistent, but I'm not sure why the default is being changed. How many discs are bigger than 2"?

**Comment by jeffjennings** [comment]
Thanks Marco. Yes Richard and I have both been using 3.0" as default, and
it's stable. He's seen this and is good with it.

**Comment by rbooth200** [comment]
I haven't been using anything as a default, but it is definitely better to err large rather than small and I think 100 points per arcsec is a nice default resolution (although maybe slightly low).

**Comment by mtazzari** [comment]
Exactly, that is my point. 0.01" can be only a factor 2.5x smaller than the beam for DSHARP-like obs.
In CLEAN, you would choose 1/3-1/5.
Is it feasible 200 points per arcsec, i.e. 0.005"? This should cover pretty much all observations.

**Comment by rbooth200** [comment]
Yeah 200 points per arsec is better for AS 209. It's take 8x longer if we push it to ~600 bins though. I think 300 + 2" is maybe a better choice

**Comment by jeffjennings** [comment]
300 + 2" is fine. Happy to give a sense of the minimal 'resolution' that
the fit should apply when the user chooses Rout and nbins.

**Comment by rbooth200** [comment]
I think we should just add a comment to the docs that people should check this.

**Comment by jeffjennings** [comment]
> I think we should just add a comment to the docs that people should check this.

yes that's what I mean, I'll add to thee quickstart.

**Comment by jeffjennings** [comment]
I've opened #88 to address adding an explanation of suggested ranges for hyperprior values to the docs. That can go in a later PR; I've changed the default `Rout` back to 2". This PR for me is ready to merge.

**Comment by mtazzari** [comment]
Great. I suggest you do the change to the quickstart within this PR so it is self-contained.

**Comment by mtazzari** [comment]
Oh ok, forget my last comment. I didn't see you pushed the new commit. Fine to merge then

**Comment by jeffjennings** [comment]
I suggest keeping it separate because it won't be a single sentence; it will need to be a dedicated page that succinctly discusses the suggested choices/ranges for all hyperpriors and demonstrates how to overplot fits to the same dataset under multiple hyperprior choices.

**Comment by jeffjennings** [comment]
Great, sounds good!

**Pull request merged**
